### PR TITLE
Replace cross tests for native tests

### LINKED ISSUE #7: Replace direct `Command` by crates in the build script
Currently, the build script contains two direct commands to `wget` and `tar`. Those are not very portable and require use to have a `Dockerfile` that installs `wget`.
As suggested in #6 a better option would be to use the [curl](https://github.com/alexcrichton/curl-rust) crate and [flate2 and tar](https://rust-lang-nursery.github.io/rust-cookbook/compression/tar.html) instead.

I did try that change in the PR mentionned above but faced the following issue when cross compiling:
```
= note: /usr/bin/ld: /target/debug/deps/libopenssl_sys-07dcfde38d575d2d.rlib(s3_clnt.o): Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /target/debug/deps/libopenssl_sys-07dcfde38d575d2d.rlib(s3_clnt.o): Relocations in generic ELF (EM: 183)
          /target/debug/deps/libopenssl_sys-07dcfde38d575d2d.rlib: error adding symbols: File in wrong format
          collect2: error: ld returned 1 exit status
```
I think that is because of clash of OpenSSL libraries between the one on the host and the one used in `cross` Docker container. This needs more investigating.

### LINKED ISSUE #12: Add Travis CI tests for Aarch64
Remove cross compilation tests and test native compilation on Arm64 using Travis CI. Check how it was done on parsec repo.

### LINKED ISSUE #17: Build fails with confusing message if wget is not available
Found by @paulhowardarm - if `wget` is not installed on the machine running a build of `parsec-interface-rs`, the build fails with a message saying something akin to `File or folder not found`, because it cannot find the tar archive pulled down by `wget`.

This should bomb out earlier, when running the `wget` command, but it doesn't seem to do that.

Seems somewhat related to #7

### PR DESCRIPTION
**Pull request by hug-dev**
Uses Travis CI for Arm64 tests. Adds the Travis CI YAML file and also
replace the Command structure in the build script with Rust native
crates.

Signed-off-by: Hugues de Valon <hugues.devalon@arm.com>

Close #17
Close #12
Close #7 

3 in a row 🔫

### CODE REVIEW

File: build.rs [hunk 1]
```diff
@@ -52,37 +54,35 @@ fn generate_proto_sources() -> Result<()> {
...
-            PARSEC_OPERATIONS_VERSION
-        ))
-        .arg("--directory")
-        .arg(env::var("OUT_DIR").unwrap())
-        .status()?
-        .success()
+    let mut buf = Vec::new();
+    let mut handle = Easy::new();
+    handle.url(&protobuf_archive_url)?;
     {
```
Comment (ionut-arm) [inline build.rs]: Is this needed to drop `transfer` at the end of the block?

Comment (hug-dev) [reply build.rs]: yes exactly so that the mutable reference on `buf` is dropped as well and it can be used again in line 77
